#ifndef DICE_PROJECT_CONSTANTS_H
#define DICE_PROJECT_CONSTANTS_H

#define IMG_SIZE 9
#define NB_CLASS 6
#define EXPORT_DATA true
#define MAX_DATA_TO_EXPORT 10
#define EQUAL_MARGIN 50
#define THRESHOLD 17

#endif //DICE_PROJECT_CONSTANTS_H
